CREATE TABLE "SYSMAN"."LAVIA_ITS_FREE_SPACE"
  (
    "MO_ID"        NUMBER,
    "TIME"         NUMBER,
    "CLE"          NUMBER,
    "TORQUE"       NUMBER,
    "FUEL"         NUMBER,
    "ACC_POS"      NUMBER,
    "TRAVIA"       NUMBER(38,0),
    "SPEED"        NUMBER,
    "LEGAL_SPEED"  NUMBER,
    "LATITUDE"     NUMBER,
    "LONGITUDE"    NUMBER,
    "DISTANCE"     NUMBER,
    "ACCELERATION" NUMBER,
    "BREAK"        NUMBER(38,0),
    "LAVIA"        NUMBER(38,0),
    "NO_KICKDOWN"  NUMBER(38,0),
    "RPM"          NUMBER(38,0),
    "GEAR"         NUMBER(38,0)
  );
INSERT INTO LAVIA_ITS_FREE_SPACE (
  MO_ID,TIME, CLE, TORQUE,FUEL,ACC_POS,TRAVIA,SPEED, LEGAL_SPEED,LATITUDE,LONGITUDE, DISTANCE, ACCELERATION, BREAK, LAVIA, NO_KICKDOWN,RPM, GEAR
  )
    SELECT MO_ID, TIME, ((LATITUDE+17) + (((LATITUDE+17)*31) + LONGITUDE)) , TORQUE,FUEL,ACC_POS,TRAVIA,SPEED, LEGAL_SPEED,LATITUDE,LONGITUDE, DISTANCE, ACCELERATION, BREAK, LAVIA, NO_KICKDOWN,RPM, GEAR
    FROM lavia_its;